- name: Deploy OVF to ESXi
  hosts: localhost
  gather_facts: false
  collections:
    - community.vmware

  tasks:
    - name: Deploy the OVF
      community.vmware.vmware_deploy_ovf:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_pass }}"
        validate_certs: false
        ovf: "{{ ovf_path }}"
        name: "{{ vm_name }}"
        datacenter: "ha-datacenter"
        datastore: "DS1"
        networks:
          nat: "VM Network"
        wait: yes
